[build]
  command = "npm run build"
  publish = "dist"
  environment = [
    "SECRETS_SCAN_SMART_DETECTION_OMIT_VALUES",
    "VITE_FIREBASE_API_KEY"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
